name: Protobuf Checks
# This workflow runs some Protobuf related checks.
on:
  pull_request:
    paths:
      - "**/**.proto"
      - "**/go.mod"
      - ".github/workflows/proto.yml"

jobs:
  buf_lint:
    runs-on: ubuntu-latest
    name: Protobuf Checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.5.0
      - uses: bufbuild/buf-lint-action@v1
        if: always()
        with:
          input: 'proto'
      - uses: bufbuild/buf-breaking-action@v1
        if: always()
        with:
          input: 'proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'buf.build/provenance-io/provenance'
      - name: proto-update-check
        if: always()
        run: make proto-update-check
      - name: third_party breaking
        if: always()
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'third_party/proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'buf.build/provenance-io/third-party'
